### ISSUE TITLE
function 'as_cholmod_sparse' not provided by package 'Matrix' due to Matrix version

### ISSUE THREAD

**Issue by acihanckr** [chernolabs/scX#7]
Very nice package, thanks for the work. When I ran createSCEobject function with your example data (the following code), I ran into the following error. When I looked for similar issues I figured out it is due to Matrix package version. So downgrading Matrix to 1.6-1 will fix the problem but in that case Seurat will not load since SeuratObject requires Matrix>=1.6-3.

````
library(scX)
cseo <- createSCEobject(xx = scXample, 
                        partitionVars = "inferred_cell_type", 
                        metadataVars = c("source_name", "age", "sex", "strain", "treatment", "pseudotime"),
                        descriptionText = "Quick Start Guide")

launch_scX(cseo)


Creating SCE object... Finished
Changing factors from partitionVars... Finished
Computing QC metrics... Finished
Computing normalization...Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'
````

**Comment by mluzvercesi** [comment]
Hey, thanks for reporting this!

That is indeed an issue with the latest version of `Matrix`, relative to `irlba` which calls that function. As reported in https://github.com/bwlewis/irlba/issues/70, re-installing that package after having the latest `Matrix` version fixes that:

```
remove.packages("irlba")
install.packages("irlba")
```
Hope this works!

**Comment by Zhanghan1024** [comment]
cds = preprocess_cds(cds, num_dim = 100)
Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'
remove.packages("irlba")
install.packages("irlba") 
and restart, it is work!
